server:
  port: 9297
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/riskigalangsaputra/config-server-microservice
          clone-on-start: true
    compatibility-verifier:
      enabled: false
